---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flaskapp-hpa
  namespace: flaskapp-nikola
  apiVersion: apps/v1
spec:
  scaleTargetRef:
    kind: Deployment
    name: flaskapp-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80