---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flaskapp-nikola
  labels:
    app: flaskapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: flaskapp
  type: LoadBalancer
