name: CI/CD

on:
  push:
    branches: [main]
    paths:
      - webapp/**

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
        env:
          db_uri: ${{ secrets.DB_URI }}
          secret_key: ${{ secrets.SECRET_KEY }}
          driver_location: ${{ secrets.DRIVER_LOCATION }}
          app_url: ${{ secrets.APP_URL }}
      - name: Setup selenium
        run: |
          sudo pip3 install selenium
      - name: Setup chrome
        run: |
          sudo apt-get install google-chrome-stable 
          sudo apt-get install -y unzip   
          wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip 
          unzip chromedriver_linux64.zip 
          sudo mv chromedriver /usr/bin/chromedriver
      - name: Setup app
        run: |
          sudo pip3 install -r requirements.txt
      - name: Export env var
        run: |
          export db_uri secret_key app_url driver_location
      - name: Start the app
        run: |
          sudo python3 run.py &
      - name: Run the tests
        run: |
          sudo python3 test.py

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Logs onto Docker using secret credentials

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker build image with python app

        run: |
          docker build . -t t0b9/flask-app-nikola:latest

      - name: Docker push created image

        run: |
          docker push t0b9/flask-app-nikola:latest
