name: BuildDockerImageCI

on:
  push:
    branches: [ main ]
    paths:
      - webapp/**
  pull_request:
    branches: [ main ]

jobs:

  build:
     runs-on: ubuntu-latest
     steps:
          - uses: actions/checkout@v2
          # Logs onto Docker using secret credentials
          
          - name: Docker login
            env:
              DOCKER_USER: ${{ secrets.DOCKER_USER }}
              DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            run: |
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              
              
          - name: Docker build image with python app

            run: |
              docker build . -t t0b9/flask-app-nikola:latest
              
              
          - name: Docker push created image

            run: |
              docker push t0b9/flask-app-nikola:latest
